/* Script to stamp a build version into the Angular app.
 *
 * Generates `src/app/version.ts` with a version string derived from
 * package.json's version field plus a UTC build timestamp.
 *
 * Usage:
 *   pnpm exec ts-node --project tsconfig.node.json scripts/stamp-version.ts
 *
 * This is automatically invoked via the "prebuild" npm script, so every
 * `pnpm run build` (and therefore every deploy) produces a fresh version.
 */

import * as fs from 'fs';
import * as path from 'path';

const rootDir = path.resolve(__dirname, '..');
const pkg = JSON.parse(
  fs.readFileSync(path.join(rootDir, 'package.json'), 'utf-8')
);

// Build a compact UTC timestamp: YYYY-MM-DDTHH:MM
const now = new Date();
const pad = (n: number) => String(n).padStart(2, '0');
const timestamp = [
  now.getUTCFullYear(),
  '-',
  pad(now.getUTCMonth() + 1),
  '-',
  pad(now.getUTCDate()),
  'T',
  pad(now.getUTCHours()),
  ':',
  pad(now.getUTCMinutes()),
].join('');

const version = `${pkg.version}+${timestamp}`;

const outFile = path.join(rootDir, 'src', 'app', 'version.ts');
const content = `/* Auto-generated by scripts/stamp-version.ts — do not edit manually. */
export const APP_VERSION = '${version}';
`;

fs.writeFileSync(outFile, content, 'utf-8');
console.log(`Stamped version: ${version}  →  ${outFile}`);
