/* journeys-catalog.ts
 *
 * Authoritative registry of User Personas, Core Journeys, and the 97+ View Site Surface Map.
 */

import { UserJourneyEntry, SiteSurfaceEntry, UserActor } from '../models/user-journey';

export const USER_JOURNEYS_CATALOG: UserJourneyEntry[] = [
  {
    id: 'grading-progression',
    title: 'Grading Request, Examination & Level Progression',
    primaryActor: UserActor.Member,
    primaryTaxonomyNodeId: 'grading-candidate',
    participatingActors: [UserActor.Member, UserActor.Instructor, UserActor.EventOrganizer, UserActor.HQAdmin],
    participatingTaxonomyNodeIds: ['grading-candidate', 'sifu-instructor', 'grading-examiner', 'event-organizer', 'hq-admin'],
    summary:
      'From checking eligibility and requesting an exam to Sifu approval, event linkage, examiner evaluation, and automated digital passbook level advancement.',
    steps: [
      {
        stepId: 'step-grading-1',
        stepNumber: 1,
        actor: UserActor.Member,
        actorTaxonomyId: 'grading-candidate',
        title: 'Check Next Eligible Level',
        description: 'Member reviews their current Student/Application level on /me and checks next owed level.',
        screenViewId: 'myProfile',
        screenPath: '/me',
        mutatedDataTypes: [],
      },
      {
        stepId: 'step-grading-2',
        stepNumber: 2,
        actor: UserActor.Member,
        actorTaxonomyId: 'grading-candidate',
        title: 'Submit Request or Purchase',
        description: 'Member requests grading with preferred instructor or pays fee via Stripe.',
        screenViewId: 'nextGrading',
        screenPath: '/gradings/next',
        mutatedDataTypes: ['grading', 'order'],
        triggeredFlow: 'client-reactivity',
        handoff: {
          targetTaxonomyId: 'sifu-instructor',
          targetTaxonomyName: 'Certified Instructor (Sifu)',
          targetJourneyId: 'grading-progression',
          targetJourneyTitle: 'Grading Request, Examination & Level Progression',
          targetStepNumber: 3,
          targetStepTitle: 'Sifu Reviews & Accepts',
          interactionType: 'approval_request',
          description: 'Submits student examination application to primary instructor (Sifu) for readiness review and syllabus acceptance.',
        },
      },
      {
        stepId: 'step-grading-3',
        stepNumber: 3,
        actor: UserActor.Instructor,
        actorTaxonomyId: 'sifu-instructor',
        title: 'Sifu Reviews & Accepts',
        description: 'Primary instructor reviews request on /gradings/:id and marks status Accepted.',
        screenViewId: 'gradingView',
        screenPath: '/gradings/:id',
        mutatedDataTypes: ['grading'],
        triggeredFlow: 'trigger-mirroring',
        receivedFrom: {
          targetTaxonomyId: 'grading-candidate',
          targetTaxonomyName: 'Grading Candidate',
          targetJourneyId: 'grading-progression',
          targetJourneyTitle: 'Grading Request, Examination & Level Progression',
          targetStepNumber: 2,
          targetStepTitle: 'Submit Request or Purchase',
          interactionType: 'approval_request',
          description: 'Received student grading application pending eligibility confirmation.',
        },
        handoff: {
          targetTaxonomyId: 'grading-examiner',
          targetTaxonomyName: 'Grading Examiner',
          targetJourneyId: 'grading-progression',
          targetJourneyTitle: 'Grading Request, Examination & Level Progression',
          targetStepNumber: 4,
          targetStepTitle: 'Conduct Exam & Record Result',
          interactionType: 'evaluation',
          description: 'Hands off approved candidate to certified Examiner for formal curriculum evaluation and feedback.',
        },
      },
      {
        stepId: 'step-grading-4',
        stepNumber: 4,
        actor: UserActor.Instructor,
        actorTaxonomyId: 'grading-examiner',
        title: 'Conduct Exam & Record Result',
        description: 'Examiner tests student and records Pass or Not-Passed with detailed feedback notes.',
        screenViewId: 'gradingView',
        screenPath: '/gradings/:id',
        mutatedDataTypes: ['grading', 'member'],
        triggeredFlow: 'trigger-mirroring',
        receivedFrom: {
          targetTaxonomyId: 'sifu-instructor',
          targetTaxonomyName: 'Certified Instructor (Sifu)',
          targetJourneyId: 'grading-progression',
          targetJourneyTitle: 'Grading Request, Examination & Level Progression',
          targetStepNumber: 3,
          targetStepTitle: 'Sifu Reviews & Accepts',
          interactionType: 'evaluation',
          description: 'Examiner tests student curriculum following Sifu approval.',
        },
        handoff: {
          targetTaxonomyId: 'hq-admin',
          targetTaxonomyName: 'HQ System Administrator',
          targetJourneyId: 'member-onboarding',
          targetJourneyTitle: 'Member Registration, Verification & Digital Passbook',
          targetStepNumber: 4,
          targetStepTitle: 'View Digital Passbook',
          interactionType: 'fulfillment',
          description: 'Result saved; triggers automated passbook level advancement and digital certificate issuance.',
        },
      },
    ],
    relatedStories: ['grading-sifu-notifications', 'grading-request-acceptance', 'grading-result-recorded', 'grading-event-managers', 'grading-unpaid-request-guard'],
    relatedDataTypes: ['grading', 'member', 'ilc-event', 'order'],
    relatedFlows: ['client-reactivity', 'trigger-mirroring'],
    relatedPatterns: ['init-zero-default-converter', 'dynamic-derived-permissions', 'zoneless-signals-onpush'],
    setupPrerequisites: ['firebase-emulators', 'emulator-seeding-testing'],
  },
  {
    id: 'member-onboarding',
    title: 'Member Registration, Verification & Digital Passbook',
    primaryActor: UserActor.Member,
    primaryTaxonomyNodeId: 'prospective-member',
    participatingActors: [UserActor.Member, UserActor.HQAdmin],
    participatingTaxonomyNodeIds: ['prospective-member', 'student-practitioner', 'active-member', 'hq-admin'],
    summary:
      'New practitioner signs up, pays annual membership fee, receives assigned Member ID, and accesses their digital passbook.',
    steps: [
      {
        stepId: 'step-onboarding-1',
        stepNumber: 1,
        actor: UserActor.PublicVisitor,
        actorTaxonomyId: 'prospective-member',
        title: 'Select Membership Tier',
        description: 'Visitor navigates to /become-a-member and selects membership type.',
        screenViewId: 'becomeAMember',
        screenPath: '/become-a-member',
      },
      {
        stepId: 'step-onboarding-2',
        stepNumber: 2,
        actor: UserActor.Member,
        actorTaxonomyId: 'student-practitioner',
        title: 'Complete Stripe Checkout',
        description: 'User enters details and pays membership subscription.',
        screenViewId: 'orderComplete',
        screenPath: '/order-complete',
        mutatedDataTypes: ['order'],
        triggeredFlow: 'ecommerce-webhooks',
        handoff: {
          targetTaxonomyId: 'hq-admin',
          targetTaxonomyName: 'HQ System Administrator',
          targetJourneyId: 'member-onboarding',
          targetJourneyTitle: 'Member Registration, Verification & Digital Passbook',
          targetStepNumber: 3,
          targetStepTitle: 'Verify & Assign Member ID',
          interactionType: 'fulfillment',
          description: 'Payment completed; hands off to HQ Administrator to allocate sequential Member ID and initialize ACL cache.',
        },
      },
      {
        stepId: 'step-onboarding-3',
        stepNumber: 3,
        actor: UserActor.HQAdmin,
        actorTaxonomyId: 'hq-admin',
        title: 'Verify & Assign Member ID',
        description: 'Admin allocates next sequential Member ID from /system/counters.',
        screenViewId: 'manageMembers',
        screenPath: '/manage-members',
        mutatedDataTypes: ['member', 'system'],
        triggeredFlow: 'trigger-mirroring',
        receivedFrom: {
          targetTaxonomyId: 'student-practitioner',
          targetTaxonomyName: 'Student Practitioner',
          targetJourneyId: 'member-onboarding',
          targetJourneyTitle: 'Member Registration, Verification & Digital Passbook',
          targetStepNumber: 2,
          targetStepTitle: 'Complete Stripe Checkout',
          interactionType: 'fulfillment',
          description: 'Received membership purchase awaiting sequential ID counter increment.',
        },
        handoff: {
          targetTaxonomyId: 'active-member',
          targetTaxonomyName: 'Active Member',
          targetJourneyId: 'member-onboarding',
          targetJourneyTitle: 'Member Registration, Verification & Digital Passbook',
          targetStepNumber: 4,
          targetStepTitle: 'View Digital Passbook',
          interactionType: 'notification',
          description: 'Member ID allocated; unlocks passbook permissions and sends welcome confirmation.',
        },
      },
      {
        stepId: 'step-onboarding-4',
        stepNumber: 4,
        actor: UserActor.Member,
        actorTaxonomyId: 'active-member',
        title: 'View Digital Passbook',
        description: 'Member views official digital passbook card, level badges, and renewal date.',
        screenViewId: 'myProfile',
        screenPath: '/me',
        mutatedDataTypes: [],
        receivedFrom: {
          targetTaxonomyId: 'hq-admin',
          targetTaxonomyName: 'HQ System Administrator',
          targetJourneyId: 'member-onboarding',
          targetJourneyTitle: 'Member Registration, Verification & Digital Passbook',
          targetStepNumber: 3,
          targetStepTitle: 'Verify & Assign Member ID',
          interactionType: 'notification',
          description: 'Passbook credentials unlocked with assigned official association ID.',
        },
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['member', 'acl', 'order', 'system'],
    relatedFlows: ['ecommerce-webhooks', 'trigger-mirroring'],
    relatedPatterns: ['fast-lookup-acl-cache', 'init-zero-default-converter'],
    setupPrerequisites: ['local-dev-setup', 'firebase-emulators'],
  },
  {
    id: 'event-hosting-ticketing',
    title: 'Event Proposal, Online Ticketing & Attendee Management',
    primaryActor: UserActor.EventOrganizer,
    primaryTaxonomyNodeId: 'event-organizer',
    participatingActors: [UserActor.EventOrganizer, UserActor.HQAdmin, UserActor.Member, UserActor.PublicVisitor],
    participatingTaxonomyNodeIds: ['event-organizer', 'hq-admin', 'active-member', 'external-attendee'],
    summary:
      'Organizer drafts a seminar, admin approves and publishes, attendees purchase tickets via Stripe, and organizer manages check-in.',
    steps: [
      {
        stepId: 'step-event-1',
        stepNumber: 1,
        actor: UserActor.EventOrganizer,
        actorTaxonomyId: 'event-organizer',
        title: 'Draft Event',
        description: 'Organizer creates event with location, dates, and ticket pricing tiers on /organise-events.',
        screenViewId: 'organiseEvents',
        screenPath: '/organise-events',
        mutatedDataTypes: ['ilc-event', 'product'],
        handoff: {
          targetTaxonomyId: 'hq-admin',
          targetTaxonomyName: 'HQ System Administrator',
          targetJourneyId: 'event-hosting-ticketing',
          targetJourneyTitle: 'Event Proposal, Online Ticketing & Attendee Management',
          targetStepNumber: 2,
          targetStepTitle: 'Approve & Publish',
          interactionType: 'approval_request',
          description: 'Submits workshop venue and ticket tiers to HQ Administrator for association sanctioning.',
        },
      },
      {
        stepId: 'step-event-2',
        stepNumber: 2,
        actor: UserActor.HQAdmin,
        actorTaxonomyId: 'hq-admin',
        title: 'Approve & Publish',
        description: 'Admin publishes event to public calendar.',
        screenViewId: 'manageEvents',
        screenPath: '/manage-events',
        mutatedDataTypes: ['ilc-event'],
        receivedFrom: {
          targetTaxonomyId: 'event-organizer',
          targetTaxonomyName: 'Event Organizer',
          targetJourneyId: 'event-hosting-ticketing',
          targetJourneyTitle: 'Event Proposal, Online Ticketing & Attendee Management',
          targetStepNumber: 1,
          targetStepTitle: 'Draft Event',
          interactionType: 'approval_request',
          description: 'Received regional workshop proposal for insurance and scheduling approval.',
        },
        handoff: {
          targetTaxonomyId: 'active-member',
          targetTaxonomyName: 'Active Member',
          targetJourneyId: 'event-hosting-ticketing',
          targetJourneyTitle: 'Event Proposal, Online Ticketing & Attendee Management',
          targetStepNumber: 3,
          targetStepTitle: 'Purchase Ticket',
          interactionType: 'notification',
          description: 'Workshop approved; publishes seminar to calendar and notifies association members.',
        },
      },
      {
        stepId: 'step-event-3',
        stepNumber: 3,
        actor: UserActor.Member,
        actorTaxonomyId: 'active-member',
        title: 'Purchase Ticket',
        description: 'Attendee selects In-Person or Online ticket tier and pays via Stripe.',
        screenViewId: 'eventRegister',
        screenPath: '/events/:id/register',
        mutatedDataTypes: ['order', 'event-registration'],
        triggeredFlow: 'ecommerce-webhooks',
        receivedFrom: {
          targetTaxonomyId: 'hq-admin',
          targetTaxonomyName: 'HQ System Administrator',
          targetJourneyId: 'event-hosting-ticketing',
          targetJourneyTitle: 'Event Proposal, Online Ticketing & Attendee Management',
          targetStepNumber: 2,
          targetStepTitle: 'Approve & Publish',
          interactionType: 'notification',
          description: 'Discovered published workshop on association calendar.',
        },
        handoff: {
          targetTaxonomyId: 'event-organizer',
          targetTaxonomyName: 'Event Organizer',
          targetJourneyId: 'event-hosting-ticketing',
          targetJourneyTitle: 'Event Proposal, Online Ticketing & Attendee Management',
          targetStepNumber: 4,
          targetStepTitle: 'Check-In Attendees',
          interactionType: 'handoff',
          description: 'Completed ticket purchase; registered on event check-in roster with digital QR ticket.',
        },
      },
      {
        stepId: 'step-event-4',
        stepNumber: 4,
        actor: UserActor.EventOrganizer,
        actorTaxonomyId: 'event-organizer',
        title: 'Check-In Attendees',
        description: 'Organizer scans tickets or checks in attendees on site.',
        screenViewId: 'eventRegistrations',
        screenPath: '/events/:id/registrations',
        mutatedDataTypes: ['event-registration'],
        receivedFrom: {
          targetTaxonomyId: 'active-member',
          targetTaxonomyName: 'Active Member',
          targetJourneyId: 'event-hosting-ticketing',
          targetJourneyTitle: 'Event Proposal, Online Ticketing & Attendee Management',
          targetStepNumber: 3,
          targetStepTitle: 'Purchase Ticket',
          interactionType: 'handoff',
          description: 'Attendee arrives at venue and presents ticket for admission scan.',
        },
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['ilc-event', 'event-registration', 'product', 'order'],
    relatedFlows: ['ecommerce-webhooks', 'micro-frontends'],
    relatedPatterns: ['early-domain-typing-snapshots', 'micro-frontend-web-components'],
    setupPrerequisites: ['firebase-emulators'],
  },
  {
    id: 'vod-streaming',
    title: 'VOD Catalog, Trailer Preview, Streaming & Offline Playback',
    primaryActor: UserActor.Member,
    primaryTaxonomyNodeId: 'student-practitioner',
    participatingActors: [UserActor.Member, UserActor.HQAdmin, UserActor.PublicVisitor],
    participatingTaxonomyNodeIds: ['anonymous-visitor', 'student-practitioner', 'active-member', 'hq-admin'],
    summary:
      'Browse instructional video catalog, watch free trailers, purchase access, stream multi-bitrate HLS, and cache for offline viewing.',
    steps: [
      {
        stepId: 'step-vod-1',
        stepNumber: 1,
        actor: UserActor.PublicVisitor,
        actorTaxonomyId: 'anonymous-visitor',
        title: 'Browse Catalog & Watch Trailer',
        description: 'User previews free trailers on /videos without login.',
        screenViewId: 'videos',
        screenPath: '/videos',
        handoff: {
          targetTaxonomyId: 'student-practitioner',
          targetTaxonomyName: 'Student Practitioner',
          targetJourneyId: 'vod-streaming',
          targetJourneyTitle: 'VOD Catalog, Trailer Preview, Streaming & Offline Playback',
          targetStepNumber: 2,
          targetStepTitle: 'Purchase Video Grant',
          interactionType: 'handoff',
          description: 'Previewed free trailer; logs in as practitioner to purchase complete video series.',
        },
      },
      {
        stepId: 'step-vod-2',
        stepNumber: 2,
        actor: UserActor.Member,
        actorTaxonomyId: 'student-practitioner',
        title: 'Purchase Video Grant',
        description: 'Member completes one-click Stripe checkout for full video access.',
        screenViewId: 'videoView',
        screenPath: '/videos/:id',
        mutatedDataTypes: ['video-grant', 'order'],
        triggeredFlow: 'ecommerce-webhooks',
        receivedFrom: {
          targetTaxonomyId: 'anonymous-visitor',
          targetTaxonomyName: 'Anonymous Visitor',
          targetJourneyId: 'vod-streaming',
          targetJourneyTitle: 'VOD Catalog, Trailer Preview, Streaming & Offline Playback',
          targetStepNumber: 1,
          targetStepTitle: 'Browse Catalog & Watch Trailer',
          interactionType: 'handoff',
          description: 'Transitioned from public trailer preview to video series purchase.',
        },
      },
      {
        stepId: 'step-vod-3',
        stepNumber: 3,
        actor: UserActor.Member,
        actorTaxonomyId: 'student-practitioner',
        title: 'Adaptive HLS Streaming',
        description: 'Video player requests signed playback session and streams adaptive HLS video.',
        screenViewId: 'videoView',
        screenPath: '/videos/:id',
        mutatedDataTypes: ['video-progress'],
        triggeredFlow: 'media-transcoding',
      },
      {
        stepId: 'step-vod-4',
        stepNumber: 4,
        actor: UserActor.Member,
        actorTaxonomyId: 'student-practitioner',
        title: 'Download for Offline',
        description: 'Member caches video segments in browser IndexedDB for offline training.',
        screenViewId: 'videoView',
        screenPath: '/videos/:id',
        mutatedDataTypes: [],
      },
      {
        stepId: 'step-vod-5',
        stepNumber: 5,
        actor: UserActor.Member,
        actorTaxonomyId: 'student-practitioner',
        title: 'Gift Video or Series',
        description: 'Member or guest clicks "Gift this Video" or "Gift this Series", provides recipient details and optional message, completing checkout with gift metadata. Stripe webhook provisions VideoGrant (kind: gift_purchase) and queues transactional email vodGiftReceived.',
        screenViewId: 'videoView',
        screenPath: '/videos/:id',
        mutatedDataTypes: ['video-grant', 'order', 'mail'],
        triggeredFlow: 'ecommerce-webhooks',
      },
      {
        stepId: 'step-vod-6',
        stepNumber: 6,
        actor: UserActor.HQAdmin,
        actorTaxonomyId: 'hq-admin',
        title: 'Admin Direct Video Access Grant',
        description: 'HQ Administrator opens Grant Access modal (/videos?grant=true), selects video or full series, enters recipient email and optional expiration, and invokes grantVideoAccess callable function. Recipient receives in-app VideoAccessGranted notification and transactional email.',
        screenViewId: 'videoView',
        screenPath: '/videos?grant=true',
        mutatedDataTypes: ['video-grant', 'mail'],
        triggeredFlow: 'media-transcoding',
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['video-item', 'video-grant', 'video-progress', 'order', 'mail'],
    relatedFlows: ['media-transcoding', 'ecommerce-webhooks'],
    relatedPatterns: ['signed-playback-offline-idb', 'resumable-chunked-uploads'],
    setupPrerequisites: ['third-party-integrations'],
  },
  {
    id: 'instructor-licensing',
    title: 'Instructor Certification & School License Oversight',
    primaryActor: UserActor.Instructor,
    primaryTaxonomyNodeId: 'sifu-instructor',
    participatingActors: [UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    participatingTaxonomyNodeIds: ['sifu-instructor', 'school-manager', 'hq-admin'],
    summary:
      'Instructors and school managers renew annual credentials, triggering automated ACL updates and student roster management.',
    steps: [
      {
        stepId: 'step-licensing-1',
        stepNumber: 1,
        actor: UserActor.Instructor,
        actorTaxonomyId: 'sifu-instructor',
        title: 'Renew Instructor License',
        description: 'Instructor purchases annual license renewal on /instructor-license-purchase.',
        screenViewId: 'instructorLicensePurchase',
        screenPath: '/instructor-license-purchase',
        mutatedDataTypes: ['order'],
        triggeredFlow: 'ecommerce-webhooks',
        handoff: {
          targetTaxonomyId: 'school-manager',
          targetTaxonomyName: 'School Manager',
          targetJourneyId: 'instructor-licensing',
          targetJourneyTitle: 'Instructor Certification & School License Oversight',
          targetStepNumber: 2,
          targetStepTitle: 'Manage Student Roster',
          interactionType: 'settlement',
          description: 'Instructor renews annual teaching license; links verified status to affiliated branch dojo.',
        },
      },
      {
        stepId: 'step-licensing-2',
        stepNumber: 2,
        actor: UserActor.Instructor,
        actorTaxonomyId: 'school-manager',
        title: 'Manage Student Roster',
        description: 'Instructor inspects student passbook levels and marks training notes.',
        screenViewId: 'instructorStudents',
        screenPath: '/instructor-students',
        mutatedDataTypes: ['member'],
        receivedFrom: {
          targetTaxonomyId: 'sifu-instructor',
          targetTaxonomyName: 'Certified Instructor (Sifu)',
          targetJourneyId: 'instructor-licensing',
          targetJourneyTitle: 'Instructor Certification & School License Oversight',
          targetStepNumber: 1,
          targetStepTitle: 'Renew Instructor License',
          interactionType: 'settlement',
          description: 'Verified instructor credential displayed on branch dojo timetable.',
        },
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['member', 'school', 'acl', 'order'],
    relatedFlows: ['ecommerce-webhooks', 'trigger-mirroring'],
    relatedPatterns: ['subcollection-mirroring-cache', 'fast-lookup-acl-cache'],
    setupPrerequisites: ['emulator-seeding-testing'],
  },
  {
    id: 'materials-download',
    title: 'Protected Instructional Materials Download & ACL Assertion',
    primaryActor: UserActor.Member,
    primaryTaxonomyNodeId: 'active-member',
    participatingActors: [UserActor.Member, UserActor.Instructor, UserActor.HQAdmin],
    participatingTaxonomyNodeIds: ['active-member', 'sifu-instructor', 'system-automation'],
    summary:
      'Members download tier-gated PDF manuals, instructor guides, and curriculum rubrics verified via Cloud Functions.',
    steps: [
      {
        stepId: 'step-materials-1',
        stepNumber: 1,
        actor: UserActor.Member,
        actorTaxonomyId: 'active-member',
        title: 'Browse Available Materials',
        description: 'Member reviews accessible materials on /my-materials based on license tier.',
        screenViewId: 'myMaterials',
        screenPath: '/my-materials',
      },
      {
        stepId: 'step-materials-2',
        stepNumber: 2,
        actor: UserActor.Member,
        actorTaxonomyId: 'active-member',
        title: 'Request Secure Download URL',
        description: 'assertResourceAccess Cloud Function validates /acl/{email} and generates signed Storage URL.',
        screenViewId: 'downloadResource',
        screenPath: '/resources/:tier/:name',
        mutatedDataTypes: [],
        handoff: {
          targetTaxonomyId: 'system-automation',
          targetTaxonomyName: 'System & Automation',
          targetJourneyId: 'materials-download',
          targetJourneyTitle: 'Protected Instructional Materials Download & ACL Assertion',
          targetStepNumber: 2,
          targetStepTitle: 'Request Secure Download URL',
          interactionType: 'fulfillment',
          description: 'Triggers assertResourceAccess Cloud Function to validate member license tier and sign GCS storage URL.',
        },
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['acl', 'member'],
    relatedFlows: ['trigger-mirroring'],
    relatedPatterns: ['fast-lookup-acl-cache'],
    setupPrerequisites: ['local-dev-setup'],
  },
  {
    id: 'push-notifications',
    title: 'Web Push Notification Lifecycle & Device Subscriptions',
    primaryActor: UserActor.Member,
    primaryTaxonomyNodeId: 'active-member',
    participatingActors: [UserActor.Member, UserActor.Instructor],
    participatingTaxonomyNodeIds: ['active-member', 'sifu-instructor', 'system-automation'],
    summary:
      'Service Worker registers device Web Push token, enabling instant push alerts when gradings are accepted or events published.',
    steps: [
      {
        stepId: 'step-push-1',
        stepNumber: 1,
        actor: UserActor.Member,
        actorTaxonomyId: 'active-member',
        title: 'Configure 2-Tier Push Preferences',
        description: 'Member toggles push preferences in settings. Account-wide globalPushEnabled and per-kind switches persist to Firestore Member doc. Per-device devicePushEnabled persists to client localStorage, ensuring muted browsers do not auto-resubscribe even if OS permissions are granted.',
        screenViewId: 'userNotificationSettings',
        screenPath: '/notifications/settings',
        mutatedDataTypes: ['member'],
      },
      {
        stepId: 'step-push-2',
        stepNumber: 2,
        actor: UserActor.Member,
        actorTaxonomyId: 'active-member',
        title: 'Receive Real-Time Alert',
        description: 'Server triggers send Web Push notification directly to registered device.',
        screenViewId: 'notifications',
        screenPath: '/notifications',
        mutatedDataTypes: [],
        receivedFrom: {
          targetTaxonomyId: 'sifu-instructor',
          targetTaxonomyName: 'Certified Instructor (Sifu)',
          targetJourneyId: 'grading-progression',
          targetJourneyTitle: 'Grading Request, Examination & Level Progression',
          targetStepNumber: 3,
          targetStepTitle: 'Sifu Reviews & Accepts',
          interactionType: 'notification',
          description: 'Push notification triggered when Sifu accepts grading request.',
        },
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['member'],
    relatedFlows: ['trigger-mirroring'],
    relatedPatterns: ['zoneless-signals-onpush', 'per-device-notification-state'],
    setupPrerequisites: ['third-party-integrations'],
  },
  {
    id: 'outbound-email-notifications',
    title: 'Outbound Email Notifications & Mail Queue Tracking',
    primaryActor: UserActor.HQAdmin,
    primaryTaxonomyNodeId: 'hq-admin',
    participatingActors: [UserActor.Member],
    participatingTaxonomyNodeIds: ['active-member'],
    summary:
      'Administrator manages global email dispatch states (Off, Paused, Active), tests Google Workspace Gmail SMTP delivery, inspects live delivery logs in the email notifications space, and retries failed messages.',
    steps: [
      {
        stepId: 'step-email-notifications-1',
        stepNumber: 1,
        actor: UserActor.HQAdmin,
        actorTaxonomyId: 'hq-admin',
        title: 'Inspect Dispatch Status & Configure Templates',
        description:
          'Administrator visits /email-notifications, reviews the global 3-state banner (Off/Paused/Active), and edits template markdown in the Onboarding, Purchases, or Upcoming Events tabs.',
        screenViewId: 'emailNotifications',
        screenPath: '/email-notifications',
        mutatedDataTypes: ['mail-settings'],
        triggeredFlow: 'email-queue-processor',
      },
      {
        stepId: 'step-email-notifications-2',
        stepNumber: 2,
        actor: UserActor.HQAdmin,
        actorTaxonomyId: 'hq-admin',
        title: 'Verify SMTP via Test Email Tool',
        description:
          'Admin selects a preset in the Test Email Sender tab, previews the rendered HTML, and sends a test message. The document is enqueued with metadata.adminTest = true, bypassing Off and Paused states.',
        screenViewId: 'emailNotifications',
        screenPath: '/email-notifications?tab=test',
        mutatedDataTypes: ['mail'],
        triggeredFlow: 'email-queue-processor',
      },
      {
        stepId: 'step-email-notifications-3',
        stepNumber: 3,
        actor: UserActor.HQAdmin,
        actorTaxonomyId: 'hq-admin',
        title: 'Activate Outbound Dispatch',
        description:
          'Administrator sets status to Active via setMailSendingState. All held PAUSED placeholder documents are batch-transitioned to PENDING with dynamic template interpretation.',
        screenViewId: 'emailNotifications',
        screenPath: '/email-notifications',
        mutatedDataTypes: ['mail-settings', 'mail'],
        triggeredFlow: 'email-queue-processor',
        handoff: {
          targetTaxonomyId: 'active-member',
          targetTaxonomyName: 'Active Member',
          targetJourneyId: 'member-onboarding',
          targetJourneyTitle: 'Member Registration, Verification & Digital Passbook',
          targetStepNumber: 4,
          targetStepTitle: 'View Digital Passbook',
          interactionType: 'fulfillment',
          description: 'Active mail sending delivers automated welcome onboarding notifications and purchase receipts.',
        },
      },
      {
        stepId: 'step-email-notifications-4',
        stepNumber: 4,
        actor: UserActor.HQAdmin,
        actorTaxonomyId: 'hq-admin',
        title: 'Monitor Mail Queue, Edit Items & Inspect Deliveries',
        description:
          'Administrator monitors the Mail Logs & Queue tab with direct URL parameter navigation (?mailId=...), inspects recipient headers, edits queued message content, performs batch queue deletions, and retries failed delivery attempts via retryMailItem.',
        screenViewId: 'emailNotifications',
        screenPath: '/email-notifications?tab=logs',
        mutatedDataTypes: ['mail'],
        triggeredFlow: 'email-queue-processor',
      },
    ],
    relatedStories: ['email-notifications-dispatch'],
    relatedDataTypes: ['mail', 'mail-settings', 'order', 'member'],
    relatedFlows: ['email-queue-processor', 'one-click-unsubscribe'],
    relatedPatterns: ['mail-sending-status-lifecycle'],
    setupPrerequisites: ['email-smtp-setup'],
  },
];

export const SITE_SURFACE_MAP: SiteSurfaceEntry[] = [
  {
    viewId: 'home',
    pathPattern: '/',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Landing page for guests; digital passbook summary and quick actions for logged-in members.',
    actions: ['View passbook', 'Renew membership', 'Quick jump to gradings or calendar', 'Sign in / Sign out'],
    componentFile: 'src/app/home/home.ts',
  },
  {
    viewId: 'myProfile',
    pathPattern: '/me',
    permittedRoles: [UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Detailed digital passbook and profile self-service editor.',
    actions: ['Edit contact info', 'View student level', 'View application level', 'View membership expiry'],
    componentFile: 'src/app/member-view/member-view.ts',
  },
  {
    viewId: 'gradingView',
    pathPattern: '/gradings/:id',
    permittedRoles: [UserActor.Member, UserActor.Instructor, UserActor.EventOrganizer, UserActor.HQAdmin],
    objective: 'Detailed grading examination record with status progression tracker.',
    actions: ['Accept request', 'Decline request', 'Record pass/fail result', 'Enter examiner notes', 'Link event'],
    componentFile: 'src/app/grading-view/grading-view.ts',
  },
  {
    viewId: 'manageGradings',
    pathPattern: '/manage-gradings',
    permittedRoles: [UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Global or instructor-scoped grading queue with search and status filters.',
    actions: ['Filter by status (pending, in-review, passed)', 'Search by student name or ID', 'Open grading record'],
    componentFile: 'src/app/grading-list/grading-list.ts',
  },
  {
    viewId: 'eventsCalendar',
    pathPattern: '/events',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Global schedule of retreats, seminars, workshops, and grading camps.',
    actions: ['Filter by location or instructor', 'View event detail', 'Register for tickets', 'Add to Google Calendar'],
    componentFile: 'src/app/events-calendar/events-calendar.ts',
  },
  {
    viewId: 'eventEdit',
    pathPattern: '/events/:id/edit',
    permittedRoles: [UserActor.EventOrganizer, UserActor.HQAdmin],
    objective: 'Full event editor and ticketing configuration form.',
    actions: ['Edit dates and location', 'Manage ticket pricing tiers', 'Add co-managers', 'Publish event'],
    componentFile: 'src/app/event-edit/event-edit.ts',
  },
  {
    viewId: 'videos',
    pathPattern: '/videos',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'VOD instructional video catalog with filter tags, trailer previews, and series browsing.',
    actions: ['Browse catalog', 'Watch free trailer', 'Filter by series / level', 'Purchase full access', 'Gift video or series', 'Open admin grant modal (?grant=true)'],
    componentFile: 'src/app/videos-catalog/videos-catalog.ts',
  },
  {
    viewId: 'videoView',
    pathPattern: '/videos/:id',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'HLS video player page with timestamp chapters, gifting modal, and offline caching.',
    actions: ['Play adaptive stream', 'Resume playback', 'Download for offline', 'Bookmark time ranges', 'Gift this video', 'Gift full series', 'Admin grant access'],
    componentFile: 'src/app/video-view/video-view.ts',
  },
  {
    viewId: 'grantVodModal',
    pathPattern: '/videos?grant=true',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Modal dialog to grant access to individual videos or full series to any member or external email.',
    actions: ['Search video or series', 'Input recipient email and name', 'Toggle recipient email notification', 'Set optional expiration date and notes', 'Execute grantVideoAccess callable'],
    componentFile: 'src/app/grant-vod-modal/grant-vod-modal.ts',
  },
  {
    viewId: 'manageVod',
    pathPattern: '/manage-vod',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Administrative video curation, transcoding pipeline monitor, and Stripe price link.',
    actions: ['Upload video master with chunked resumable upload and 24h timeout', 'Trigger GCP Transcoder', 'Curate title and description', 'Attach trailer', 'Grant video access modal'],
    componentFile: 'src/app/manage-vod/manage-vod.ts',
  },
  {
    viewId: 'findAnInstructor',
    pathPattern: '/instructors',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Global certified instructor directory with map/country filters.',
    actions: ['Search by name or country', 'View instructor bio and credentials', 'Contact instructor'],
    componentFile: 'src/app/find-an-instructor/find-an-instructor.ts',
  },
  {
    viewId: 'schoolView',
    pathPattern: '/schools/:id',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'School profile page showing location, schedule, instructors, and student roster.',
    actions: ['Edit school details', 'Manage student roster', 'Renew school license', 'View school calendar'],
    componentFile: 'src/app/school-view/school-view.ts',
  },
  {
    viewId: 'manageMembers',
    pathPattern: '/manage-members',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Complete administrative directory of all practitioners across the globe.',
    actions: ['Search members', 'Edit rank and license', 'Export CSV', 'Manage admin privileges'],
    componentFile: 'src/app/member-list/member-list.ts',
  },
  {
    viewId: 'manageOrders',
    pathPattern: '/manage-orders',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Global transaction ledger of all Stripe, Squarespace, and imported orders.',
    actions: ['Inspect order line items', 'Filter by source or payment status', 'Manual settlement override'],
    componentFile: 'src/app/order-list/order-list.ts',
  },
  {
    viewId: 'emailNotifications',
    pathPattern: '/email-notifications',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Dedicated email notifications space with 3-state dispatch management, template editors, test sender, and live mail queue monitoring.',
    actions: ['Toggle dispatch state (Off, Paused, Active)', 'Edit email templates', 'Send admin test emails', 'Inspect delivery logs', 'Retry failed emails'],
    componentFile: 'src/app/email-notifications/email-notifications.component.ts',
  },
];
