/* journeys-catalog.ts
 *
 * Authoritative registry of User Personas, Core Journeys, and the 97+ View Site Surface Map.
 */

import { UserJourneyEntry, SiteSurfaceEntry, UserActor } from '../models/user-journey';

export const USER_JOURNEYS_CATALOG: UserJourneyEntry[] = [
  {
    id: 'grading-progression',
    title: 'Grading Request, Examination & Level Progression',
    primaryActor: UserActor.Member,
    participatingActors: [UserActor.Member, UserActor.Instructor, UserActor.EventOrganizer, UserActor.HQAdmin],
    summary:
      'From checking eligibility and requesting an exam to Sifu approval, event linkage, examiner evaluation, and automated digital passbook level advancement.',
    steps: [
      {
        stepNumber: 1,
        actor: UserActor.Member,
        title: 'Check Next Eligible Level',
        description: 'Member reviews their current Student/Application level on /me and checks next owed level.',
        screenViewId: 'myProfile',
        screenPath: '/me',
        mutatedDataTypes: [],
      },
      {
        stepNumber: 2,
        actor: UserActor.Member,
        title: 'Submit Request or Purchase',
        description: 'Member requests grading with preferred instructor or pays fee via Stripe.',
        screenViewId: 'nextGrading',
        screenPath: '/gradings/next',
        mutatedDataTypes: ['grading', 'order'],
        triggeredFlow: 'client-reactivity',
      },
      {
        stepNumber: 3,
        actor: UserActor.Instructor,
        title: 'Sifu Reviews & Accepts',
        description: 'Primary instructor reviews request on /gradings/:id and marks status Accepted.',
        screenViewId: 'gradingView',
        screenPath: '/gradings/:id',
        mutatedDataTypes: ['grading'],
        triggeredFlow: 'trigger-mirroring',
      },
      {
        stepNumber: 4,
        actor: UserActor.Instructor,
        title: 'Conduct Exam & Record Result',
        description: 'Examiner tests student and records Pass or Not-Passed with detailed feedback notes.',
        screenViewId: 'gradingView',
        screenPath: '/gradings/:id',
        mutatedDataTypes: ['grading', 'member'],
        triggeredFlow: 'trigger-mirroring',
      },
    ],
    relatedStories: ['grading-sifu-notifications', 'grading-request-acceptance', 'grading-result-recorded', 'grading-event-managers', 'grading-unpaid-request-guard'],
    relatedDataTypes: ['grading', 'member', 'ilc-event', 'order'],
    relatedFlows: ['client-reactivity', 'trigger-mirroring'],
    relatedPatterns: ['init-zero-default-converter', 'dynamic-derived-permissions', 'zoneless-signals-onpush'],
    setupPrerequisites: ['firebase-emulators', 'emulator-seeding-testing'],
  },
  {
    id: 'member-onboarding',
    title: 'Member Registration, Verification & Digital Passbook',
    primaryActor: UserActor.Member,
    participatingActors: [UserActor.Member, UserActor.HQAdmin],
    summary:
      'New practitioner signs up, pays annual membership fee, receives assigned Member ID, and accesses their digital passbook.',
    steps: [
      {
        stepNumber: 1,
        actor: UserActor.PublicVisitor,
        title: 'Select Membership Tier',
        description: 'Visitor navigates to /become-a-member and selects membership type.',
        screenViewId: 'becomeAMember',
        screenPath: '/become-a-member',
      },
      {
        stepNumber: 2,
        actor: UserActor.Member,
        title: 'Complete Stripe Checkout',
        description: 'User enters details and pays membership subscription.',
        screenViewId: 'orderComplete',
        screenPath: '/order-complete',
        mutatedDataTypes: ['order'],
        triggeredFlow: 'ecommerce-webhooks',
      },
      {
        stepNumber: 3,
        actor: UserActor.HQAdmin,
        title: 'Verify & Assign Member ID',
        description: 'Admin allocates next sequential Member ID from /system/counters.',
        screenViewId: 'manageMembers',
        screenPath: '/manage-members',
        mutatedDataTypes: ['member', 'system'],
        triggeredFlow: 'trigger-mirroring',
      },
      {
        stepNumber: 4,
        actor: UserActor.Member,
        title: 'View Digital Passbook',
        description: 'Member views official digital passbook card, level badges, and renewal date.',
        screenViewId: 'myProfile',
        screenPath: '/me',
        mutatedDataTypes: [],
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['member', 'acl', 'order', 'system'],
    relatedFlows: ['ecommerce-webhooks', 'trigger-mirroring'],
    relatedPatterns: ['fast-lookup-acl-cache', 'init-zero-default-converter'],
    setupPrerequisites: ['local-dev-setup', 'firebase-emulators'],
  },
  {
    id: 'event-hosting-ticketing',
    title: 'Event Proposal, Online Ticketing & Attendee Management',
    primaryActor: UserActor.EventOrganizer,
    participatingActors: [UserActor.EventOrganizer, UserActor.HQAdmin, UserActor.Member, UserActor.PublicVisitor],
    summary:
      'Organizer drafts a seminar, admin approves and publishes, attendees purchase tickets via Stripe, and organizer manages check-in.',
    steps: [
      {
        stepNumber: 1,
        actor: UserActor.EventOrganizer,
        title: 'Draft Event',
        description: 'Organizer creates event with location, dates, and ticket pricing tiers on /organise-events.',
        screenViewId: 'organiseEvents',
        screenPath: '/organise-events',
        mutatedDataTypes: ['ilc-event', 'product'],
      },
      {
        stepNumber: 2,
        actor: UserActor.HQAdmin,
        title: 'Approve & Publish',
        description: 'Admin publishes event to public calendar.',
        screenViewId: 'manageEvents',
        screenPath: '/manage-events',
        mutatedDataTypes: ['ilc-event'],
      },
      {
        stepNumber: 3,
        actor: UserActor.Member,
        title: 'Purchase Ticket',
        description: 'Attendee selects In-Person or Online ticket tier and pays via Stripe.',
        screenViewId: 'eventRegister',
        screenPath: '/events/:id/register',
        mutatedDataTypes: ['order', 'event-registration'],
        triggeredFlow: 'ecommerce-webhooks',
      },
      {
        stepNumber: 4,
        actor: UserActor.EventOrganizer,
        title: 'Check-In Attendees',
        description: 'Organizer scans tickets or checks in attendees on site.',
        screenViewId: 'eventRegistrations',
        screenPath: '/events/:id/registrations',
        mutatedDataTypes: ['event-registration'],
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['ilc-event', 'event-registration', 'product', 'order'],
    relatedFlows: ['ecommerce-webhooks', 'micro-frontends'],
    relatedPatterns: ['early-domain-typing-snapshots', 'micro-frontend-web-components'],
    setupPrerequisites: ['firebase-emulators'],
  },
  {
    id: 'vod-streaming',
    title: 'VOD Catalog, Trailer Preview, Streaming & Offline Playback',
    primaryActor: UserActor.Member,
    participatingActors: [UserActor.Member, UserActor.HQAdmin, UserActor.PublicVisitor],
    summary:
      'Browse instructional video catalog, watch free trailers, purchase access, stream multi-bitrate HLS, and cache for offline viewing.',
    steps: [
      {
        stepNumber: 1,
        actor: UserActor.PublicVisitor,
        title: 'Browse Catalog & Watch Trailer',
        description: 'User previews free trailers on /videos without login.',
        screenViewId: 'videos',
        screenPath: '/videos',
      },
      {
        stepNumber: 2,
        actor: UserActor.Member,
        title: 'Purchase Video Grant',
        description: 'Member completes one-click Stripe checkout for full video access.',
        screenViewId: 'videoView',
        screenPath: '/videos/:id',
        mutatedDataTypes: ['video-grant', 'order'],
        triggeredFlow: 'ecommerce-webhooks',
      },
      {
        stepNumber: 3,
        actor: UserActor.Member,
        title: 'Adaptive HLS Streaming',
        description: 'Video player requests signed playback session and streams adaptive HLS video.',
        screenViewId: 'videoView',
        screenPath: '/videos/:id',
        mutatedDataTypes: ['video-progress'],
        triggeredFlow: 'media-transcoding',
      },
      {
        stepNumber: 4,
        actor: UserActor.Member,
        title: 'Download for Offline',
        description: 'Member caches video segments in browser IndexedDB for offline training.',
        screenViewId: 'videoView',
        screenPath: '/videos/:id',
        mutatedDataTypes: [],
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['video-item', 'video-grant', 'video-progress', 'order'],
    relatedFlows: ['media-transcoding', 'ecommerce-webhooks'],
    relatedPatterns: ['signed-playback-offline-idb'],
    setupPrerequisites: ['third-party-integrations'],
  },
  {
    id: 'instructor-licensing',
    title: 'Instructor Certification & School License Oversight',
    primaryActor: UserActor.Instructor,
    participatingActors: [UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    summary:
      'Instructors and school managers renew annual credentials, triggering automated ACL updates and student roster management.',
    steps: [
      {
        stepNumber: 1,
        actor: UserActor.Instructor,
        title: 'Renew Instructor License',
        description: 'Instructor purchases annual license renewal on /instructor-license-purchase.',
        screenViewId: 'instructorLicensePurchase',
        screenPath: '/instructor-license-purchase',
        mutatedDataTypes: ['order'],
        triggeredFlow: 'ecommerce-webhooks',
      },
      {
        stepNumber: 2,
        actor: UserActor.Instructor,
        title: 'Manage Student Roster',
        description: 'Instructor inspects student passbook levels and marks training notes.',
        screenViewId: 'instructorStudents',
        screenPath: '/instructor-students',
        mutatedDataTypes: ['member'],
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['member', 'school', 'acl', 'order'],
    relatedFlows: ['ecommerce-webhooks', 'trigger-mirroring'],
    relatedPatterns: ['subcollection-mirroring-cache', 'fast-lookup-acl-cache'],
    setupPrerequisites: ['emulator-seeding-testing'],
  },
  {
    id: 'materials-download',
    title: 'Protected Instructional Materials Download & ACL Assertion',
    primaryActor: UserActor.Member,
    participatingActors: [UserActor.Member, UserActor.Instructor, UserActor.HQAdmin],
    summary:
      'Members download tier-gated PDF manuals, instructor guides, and curriculum rubrics verified via Cloud Functions.',
    steps: [
      {
        stepNumber: 1,
        actor: UserActor.Member,
        title: 'Browse Available Materials',
        description: 'Member reviews accessible materials on /my-materials based on license tier.',
        screenViewId: 'myMaterials',
        screenPath: '/my-materials',
      },
      {
        stepNumber: 2,
        actor: UserActor.Member,
        title: 'Request Secure Download URL',
        description: 'assertResourceAccess Cloud Function validates /acl/{email} and generates signed Storage URL.',
        screenViewId: 'downloadResource',
        screenPath: '/resources/:tier/:name',
        mutatedDataTypes: [],
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['acl', 'member'],
    relatedFlows: ['trigger-mirroring'],
    relatedPatterns: ['fast-lookup-acl-cache'],
    setupPrerequisites: ['local-dev-setup'],
  },
  {
    id: 'push-notifications',
    title: 'Web Push Notification Lifecycle & Device Subscriptions',
    primaryActor: UserActor.Member,
    participatingActors: [UserActor.Member, UserActor.Instructor],
    summary:
      'Service Worker registers device Web Push token, enabling instant push alerts when gradings are accepted or events published.',
    steps: [
      {
        stepNumber: 1,
        actor: UserActor.Member,
        title: 'Enable Notifications',
        description: 'Member toggles notification permissions in settings.',
        screenViewId: 'notificationSettings',
        screenPath: '/settings/notifications',
        mutatedDataTypes: ['member'],
      },
      {
        stepNumber: 2,
        actor: UserActor.Member,
        title: 'Receive Real-Time Alert',
        description: 'Server triggers send Web Push notification directly to registered device.',
        screenViewId: 'notifications',
        screenPath: '/notifications',
        mutatedDataTypes: [],
      },
    ],
    relatedStories: [],
    relatedDataTypes: ['member'],
    relatedFlows: ['trigger-mirroring'],
    relatedPatterns: ['zoneless-signals-onpush'],
    setupPrerequisites: ['third-party-integrations'],
  },
];

export const SITE_SURFACE_MAP: SiteSurfaceEntry[] = [
  {
    viewId: 'home',
    pathPattern: '/',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Landing page for guests; digital passbook summary and quick actions for logged-in members.',
    actions: ['View passbook', 'Renew membership', 'Quick jump to gradings or calendar', 'Sign in / Sign out'],
    componentFile: 'src/app/home/home.ts',
  },
  {
    viewId: 'myProfile',
    pathPattern: '/me',
    permittedRoles: [UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Detailed digital passbook and profile self-service editor.',
    actions: ['Edit contact info', 'View student level', 'View application level', 'View membership expiry'],
    componentFile: 'src/app/member-view/member-view.ts',
  },
  {
    viewId: 'gradingView',
    pathPattern: '/gradings/:id',
    permittedRoles: [UserActor.Member, UserActor.Instructor, UserActor.EventOrganizer, UserActor.HQAdmin],
    objective: 'Detailed grading examination record with status progression tracker.',
    actions: ['Accept request', 'Decline request', 'Record pass/fail result', 'Enter examiner notes', 'Link event'],
    componentFile: 'src/app/grading-view/grading-view.ts',
  },
  {
    viewId: 'manageGradings',
    pathPattern: '/manage-gradings',
    permittedRoles: [UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Global or instructor-scoped grading queue with search and status filters.',
    actions: ['Filter by status (pending, in-review, passed)', 'Search by student name or ID', 'Open grading record'],
    componentFile: 'src/app/grading-list/grading-list.ts',
  },
  {
    viewId: 'eventsCalendar',
    pathPattern: '/events',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Global schedule of retreats, seminars, workshops, and grading camps.',
    actions: ['Filter by location or instructor', 'View event detail', 'Register for tickets', 'Add to Google Calendar'],
    componentFile: 'src/app/events-calendar/events-calendar.ts',
  },
  {
    viewId: 'eventEdit',
    pathPattern: '/events/:id/edit',
    permittedRoles: [UserActor.EventOrganizer, UserActor.HQAdmin],
    objective: 'Full event editor and ticketing configuration form.',
    actions: ['Edit dates and location', 'Manage ticket pricing tiers', 'Add co-managers', 'Publish event'],
    componentFile: 'src/app/event-edit/event-edit.ts',
  },
  {
    viewId: 'videos',
    pathPattern: '/videos',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'VOD instructional video catalog with filter tags and trailer previews.',
    actions: ['Browse catalog', 'Watch free trailer', 'Filter by series / level', 'Purchase full access'],
    componentFile: 'src/app/videos-catalog/videos-catalog.ts',
  },
  {
    viewId: 'videoView',
    pathPattern: '/videos/:id',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'HLS video player page with timestamp chapters and offline caching.',
    actions: ['Play adaptive stream', 'Resume playback', 'Download for offline', 'Bookmark time ranges'],
    componentFile: 'src/app/video-view/video-view.ts',
  },
  {
    viewId: 'manageVod',
    pathPattern: '/manage-vod',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Administrative video curation, transcoding pipeline monitor, and Stripe price link.',
    actions: ['Upload video master', 'Trigger GCP Transcoder', 'Curate title and description', 'Attach trailer'],
    componentFile: 'src/app/manage-vod/manage-vod.ts',
  },
  {
    viewId: 'findAnInstructor',
    pathPattern: '/instructors',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.Instructor, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'Global certified instructor directory with map/country filters.',
    actions: ['Search by name or country', 'View instructor bio and credentials', 'Contact instructor'],
    componentFile: 'src/app/find-an-instructor/find-an-instructor.ts',
  },
  {
    viewId: 'schoolView',
    pathPattern: '/schools/:id',
    permittedRoles: [UserActor.PublicVisitor, UserActor.Member, UserActor.SchoolManager, UserActor.HQAdmin],
    objective: 'School profile page showing location, schedule, instructors, and student roster.',
    actions: ['Edit school details', 'Manage student roster', 'Renew school license', 'View school calendar'],
    componentFile: 'src/app/school-view/school-view.ts',
  },
  {
    viewId: 'manageMembers',
    pathPattern: '/manage-members',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Complete administrative directory of all practitioners across the globe.',
    actions: ['Search members', 'Edit rank and license', 'Export CSV', 'Manage admin privileges'],
    componentFile: 'src/app/member-list/member-list.ts',
  },
  {
    viewId: 'manageOrders',
    pathPattern: '/manage-orders',
    permittedRoles: [UserActor.HQAdmin],
    objective: 'Global transaction ledger of all Stripe, Squarespace, and imported orders.',
    actions: ['Inspect order line items', 'Filter by source or payment status', 'Manual settlement override'],
    componentFile: 'src/app/order-list/order-list.ts',
  },
];
